global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'orders-api'
    static_configs:
      - targets: ['orders-api:80']

  - job_name: 'payment-api'
    static_configs:
      - targets: ['payment-api:80']
